FROM ubuntu:latest

RUN apt-get update && apt-get install -y python3 python3-pip

RUN mkdir /app

COPY requirements.txt /app/

WORKDIR /app

RUN pip3 install -r requirements.txt

CMD ["python3", "/app/my_script.py"]